version : '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seekhere-backend
    volumes:
      - ./backend:/seekhere/backend  # mount code
      - /seekhere/backend/node_modules  # avoid overwriting node_modules
    env_file:
      - ./.env
    ports:
      - "${PORT:-5000}:5000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
    # command: >
    #   sh -c "
    #     npx prisma migrate deploy &&
    #     npx prisma generate &&
    #     npm run dev
    #   "

    networks:
      - my-network
  redis:
    image: "redis:8-alpine" 
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: redis
    ports:
      - "6379:6379" 
    volumes:
      - redis-data:/data
    networks:
      - my-network

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    healthcheck:
      test: ["CMD", "bash", "-c", "kafka-topics --bootstrap-server=kafka:9092 --list || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      CLUSTER_ID: "Qd2A87bxR52L3iLTrkwjmA" # generated UUID
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - my-network

  postgres:
    image: postgres:17-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-abhi}
      - POSTGRES_USER=${POSTGRES_USER:-abhi}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-abhi}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my-network

volumes:
  postgres_data:
  redis-data:
  kafka-data:
    driver: local

networks:
  my-network:
    driver: bridge

